name: CI
on:
  push:
    branches:
      - "**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v3
          with:
            fetch-depth: 0
        - uses: actions/setup-go@v3
          with:
            go-version: '1.21'
        - name: golangci-lint
          uses: golangci/golangci-lint-action@v3
          with:
            version: v1.54.2
            args: --timeout 10m
        - name: Test
          run: make test
        # - name: Build and push image to GAR
        #   uses: anothrNick/github-tag-action@1.64.0
        #   env:
        #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        #     WITH_V: true
